### ISSUE TITLE
test the project with new test.csv

### ISSUE THREAD

**Issue by yardenpage** [Maluuba/qgen-workshop#10]
I trained the model and then created questions from the given test.csv file.
Then I created a new file test.csv with new data with the same foramt.
I had a bug. When I looked in the debug, I figured out that the matrix "answers" in the end of the following code is full with zeros:

 answers = session.run(answer_tags, {
        document_tokens: batch["document_tokens"],
        document_lengths: batch["document_lengths"],
    })
    **answers = np.argmax(answers, 2)**

When I run the code with the given test.csv this matrix has also ones values and the project run successfully.
Do you have any idea how to solve this issue?
Thanks.

**Comment by juharris** [comment]
I think someone already came across this issue and found a solution: https://github.com/Maluuba/qgen-workshop/issues/3#issuecomment-383826450
they have yet to submit a PR.

**Comment by talrose01** [comment]
hey! this is just a bug that i found but anyway it is not the solution for this problem.

**Comment by tavianator** [comment]
@yardenpage Presumably your test data is dissimilar enough to the training data that the model fails to extract answers from it (or the model is just not very good...).  Any chance you can send an example document for which this happens?

**Comment by talrose01** [comment]
yes.
i would like to upload the csv file but there is an option just of text.
i will add a picture.
![image](https://user-images.githubusercontent.com/19147256/40510463-75ac9644-5fa5-11e8-9ba4-90ec71343be7.png)

**Comment by talrose01** [comment]
as you can see it just a random test

**Comment by tavianator** [comment]
Yeah I'm not surprised we don't extract any answers from things that don't look at all like news articles.  I don't think this is a bug per se, just a weakness of the model.
