### ISSUE TITLE
hidden layers

### ISSUE THREAD

**Issue by talrose01** [Maluuba/qgen-workshop#11]
can  someone tell me how many hidden layerss exist at this implementaion?
i think that 3 but not sure that i am  right.
thanks

**Comment by talrose01** [comment]
@surbhitkapoor

**Comment by tavianator** [comment]
This depends on exactly what you mean by "hidden layer."  For the answer tagging there is a bidirectional GRU layer with a dense layer on top, so you could consider the GRU layer hidden.  The question encoder/decoder is similar.  But you could also consider the word embeddings to induce another hidden layer in the network.
