### ISSUE TITLE
Where is this "glove.6B.100d.trimmed.txt" file?

### ISSUE THREAD

**Issue by amandalmia14** [Maluuba/qgen-workshop#12]
As in Glove.6B file i can see only glove.6B.100d.txt . 
Can anyone help me in this?

**Comment by tavianator** [comment]
https://github.com/Maluuba/qgen-workshop/blob/master/qgen/data.py#L224

**Comment by shloak2611** [comment]
I am facing the same issue. How will I fix this issue?

**Comment by tavianator** [comment]
@shloak2611 https://github.com/Maluuba/qgen-workshop/blob/master/qgen/data.py#L224

**Comment by anthonynwankwo** [comment]
@tavianator I'm not able to run the trim_embeddings() function to generate the glove.6B.100d.trimmed.txt file
The trim_embeddings() function encounters a **FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'** on https://github.com/Maluuba/qgen-workshop/blob/master/qgen/data.py#L208

FULL DISCLOSURE: It's possible that I'm not doing the right thing as my python experience level is Beginner/Intermediate

MY HUMBLE REQUEST: Kindly advise me on how (or assist me) to generate the glove.6B.100d.trimmed.txt file so I can continue to make progress. Thanks in advance. 

@shloak2611 @amandalmia14 kindly share insight about how you resolved the issue
@juharris @aatkinson I know you are busy but will appreciate your assistance

**Comment by tavianator** [comment]
@anthonynwankwo https://github.com/Maluuba/qgen-workshop/blob/master/qgen/data.py#L224

```shell
$ python ./qgen/data.py
```

Should do the trick.
