### ISSUE TITLE
automatic evaluation metrics

### ISSUE THREAD

**Issue by talrose01** [Maluuba/qgen-workshop#17]
i want to Evaluation the question that i create with an automatic evaluation metrics.
can you reccomend me which one to use?
is it possoble at  this project?
thanks

**Comment by tavianator** [comment]
Evaluating natural language generation is a hard problem.  IMO it's even harder for question generation than something like machine translation, because there's nearly an unlimited number of reasonable questions that could be asked about a document.

**Comment by juharris** [comment]
Like @tavianator _said_ evaluation for Natural Language Generation (NLG) is hard but we do have a repo with tools for helping to evaluate: https://github.com/Maluuba/nlg-eval
That repo has a few metrics built into it.

**Comment by talrose01** [comment]
@juharris  i will try it! thanks!
