### ISSUE TITLE
Generate Questions

### ISSUE THREAD

**Issue by surbhitkapoor** [Maluuba/qgen-workshop#5]
How do I generate a set of questions from a piece of string i.e. STORY file?

**Comment by surbhitkapoor** [comment]
I have successfully trained the model on the NewsQA dataset. How do I use the trained model to generate questions on other data or strings?

**Comment by surbhitkapoor** [comment]
And what does this output indicate in the **model.py** file?

https://github.com/Maluuba/qgen-workshop/blob/master/qgen/model.py#L150-L154

**Comment by juharris** [comment]
I don't think we have an example in this repo with how to load a trained model but you can look up how to load a trained TensorFlow model since our training code saves the model.

That code shows a generated question and answer from the test data.
