### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by surbhitkapoor** [Maluuba/qgen-workshop#6]
I have successfully trained the model on the NewsQA dataset. How do I use the trained model to generate questions on other data or strings?

And what does this output indicate in the **model.py** file?
https://github.com/Maluuba/qgen-workshop/blob/master/qgen/model.py#L150-L154

**Output:**

Question: who is the the ? ?
Answer: customers

Question: how many the will the ? ? ?
Answer: than 2,000

Question: what what is the ? ? ?
Answer: international

Question: who is the the ? ?
Answer: sonia

Question: what did the the ? ?
Answer: meet its oil supply obligations in nigeria

Question: who is is the ? ? ?
Answer: mend

**Comment by surbhitkapoor** [comment]
Are these the new questions that have been generated after training the model or this is something else?

**Comment by surbhitkapoor** [comment]
And where are questions stored that have been generated after training the model?

**Comment by juharris** [comment]
I don't think we have an example in this repo with how to load a trained model but you can look up how to load a trained TensorFlow model since our training code saves the model.

That code shows a generated questions and answers from the test data once the model has finished training.

I don't think questions are stored after the model has finished training.

**Comment by juharris** [comment]
Yep, you can just write the questions to a file.

**Comment by surbhitkapoor** [comment]
Can you please tell where the change in code have to be made so as to get the output to a file?

**Comment by tavianator** [comment]
@surbhitkapoor Just change these lines to write to a file instead of standard out: https://github.com/Maluuba/qgen-workshop/blob/master/qgen/model.py#L152

If you're wondering how to do that in Python, it's something like this:

```
with open("path/to/target/file.txt", "w") as f:
    print("The line to print", file=f)
    ...
```
