### ISSUE TITLE
error of answers matrix at the model.py

### ISSUE THREAD

**Issue by talrose01** [Maluuba/qgen-workshop#7]
#i run the code of the project... and stuck at the last part at the model of:

#- Now that we have a trained model, let's use it to generate some new questions and answers! First, #we predict some answers. Notice how we're only feeding the document itself to the model.

#all this line work fine:**

saver = tf.train.Saver()
session = tf.InteractiveSession()
saver.restore(session, "model-5")

batch = next(test_data())
batch = collapse_documents(batch)

answers = session.run(answer_tags, {
document_tokens: batch["document_tokens"],
document_lengths: batch["document_lengths"],
})

and the answers and batch matrix are looks like at the files that i upload.
the answers shape is:(15, 1156, 2)

#after that i run the line:
answers = np.argmax(answers, 2)
now the answers shape is (15, 1156)
#this matrix fool of zores:
[[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
...
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]]

then i run:
batch = expand_answers(batch, answers)

and got the error:
in ()
1 print(batch)
----> 2 batch = expand_answers(batch, answers)
3
4 helper = seq2seq.GreedyEmbeddingHelper(embedding, tf.fill([batch["size"]], START_TOKEN), END_TOKEN)
5 decoder = seq2seq.BasicDecoder(decoder_cell, helper, encoder_state, output_layer=projection)
in expand_answers(batch, answers)
32 print(new_batch)
33
---> 34 return _prepare_batch(new_batch)
35
36
in _prepare_batch(batch)
27
28 batch_size = len(batch)
---> 29 max_document_len = max(len(document) for document in document_words )
30 max_answer_len = max(len(answer) for answer in answer_indices )
31 max_question_len = max(len(question) for question in question_input_words )
ValueError: max() arg is an empty sequence

**when i take a look at the function of the error :
def expand_answers(batch, answers):
new_batch = []

for i in range(batch["size"]):
    split_answers = []
    last = None
    for j, tag in enumerate(answers[i]):
        if tag:
            if last != j - 1:
                split_answers.append([])
            split_answers[-1].append(j)
            last = j

    for answer_indices in split_answers:
        document_id = batch["document_ids"][i]
        document_text = batch["document_text"][i]
        document_words = batch["document_words"][i]
        answer_text = " ".join(document_words[i] for i in answer_indices)
        new_batch.append({
            "document_id": document_id,
            "document_text": document_text,
            "document_words": document_words,
            "answer_text": answer_text,
            "answer_indices": answer_indices,
            "question_text": "",
            "question_words": [],
        })

return _prepare_batch(new_batch)
##i found out that tag is alway 0 at the line:
for j, tag in enumerate(answers[i]):
because of it split_answers, and new_batch are [], are empty.

##may the answers is not as it should be and this is the problem.
hope that you can help me solve this issue,
tal
[answers_matrix.txt](https://github.com/Maluuba/qgen-workshop/files/1961278/answers_matrix.txt)
[batch_matrix.txt](https://github.com/Maluuba/qgen-workshop/files/1961279/batch_matrix.txt)

**Comment by Rose333** [comment]
The same problem I have, have you solved it?

**Comment by tavianator** [comment]
I reproduced this, it happens when no answers are extracted from the document.  `_prepare_batch()` can't handle the empty batch.  Will fix.

@talrose01 Thanks for the report!  In the future, it would be easier to read these if you use proper Markdown formatting, especially for code blocks.  You can delimit code with ` ``` ` or with 4 leading spaces.  See e.g. https://help.github.com/articles/basic-writing-and-formatting-syntax/

**Comment by talrose01** [comment]
In the next bugs i will try to be more clear :) Do you have any idea when it should be done ? The fix of the error? @tavianator

**Comment by talrose01** [comment]
This bug happend when i create my own data set for trying create question from another text. I create the same format of csv file as i used for training and change the text inside @tavianator

**Comment by tavianator** [comment]
> Do you have any idea when it should be done ? The fix of the error? @tavianator

There are a couple things that need to be done to fix it.  `_prepare_batch()` probably shouldn't choke on empty batches, but Tensorflow chokes on them anyway so I'll need to adapt the code to skip running inference on nothing.
