### ISSUE TITLE
Question generation from another story

### ISSUE THREAD

**Issue by surbhitkapoor** [Maluuba/qgen-workshop#9]
Is there a way to use this code to generate the questions from a random story file? I mean that can this code be modified in any way so that I can use the trained model to generate questions on a new story file?

**Comment by tavianator** [comment]
Yes, the stories used for testing as opposed to training are in test.csv: https://github.com/Maluuba/qgen-workshop/blob/master/qgen/data.py#L214

**Comment by surbhitkapoor** [comment]
But these story files also do contain questions and answers. Is it possible in any way that the test.csv contains only stories and no questions or answers?

**Comment by tavianator** [comment]
They may be in the csv file but they're not used at inference time: https://github.com/Maluuba/qgen-workshop/blob/master/qgen/model.py#L126-L129.  You can put anything in those columns, it will be ignored.

**Comment by surbhitkapoor** [comment]
I just noticed that the train.csv file contains 92550 stories i.e. whole of the stories. Hence implying that the stories present in test.csv are already present in train.csv. Thus leading to overfitting. 

Moverover I could not understand the importance of dev.csv file.
